CREATE TABLE account (
    account_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registered DATETIME NOT NULL,
    balance BIGINT NOT NULL
);

CREATE TABLE `transaction` (
    tr_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_seq BIGINT NOT NULL,
    amount BIGINT NOT NULL,
    payment_amount BIGINT NOT NULL,
    title varchar(255) NOT NULL,
    registered DATETIME NOT NULL
);
